name: Docker

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push ping service
        id: docker_build_ping
        uses: docker/build-push-action@v2
        with:
          context: ./services/ping-pong/ping
          file: ./services/ping-pong/ping/Dockerfile
          push: true
          tags: jerrinot/turbine-demo-ping:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-ping

      - name: Build and push pong service, test
        id: docker_build_pong
        uses: docker/build-push-action@v2
        with:
          context: ./services/ping-pong/pong
          file: ./services/ping-pong/pong/Dockerfile
          push: true
          tags: jerrinot/turbine-demo-pong:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-pong

      - name: Build and push hook listener service
        id: docker_build_hook_listener
        uses: docker/build-push-action@v2
        with:
          context: ./hook-listener
          file: ./hook-listener/Dockerfile
          push: true
          tags: jerrinot/turbine-demo-hook-listener:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-hook

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          cp -rn /tmp/.buildx-cache-ping/* /tmp/.buildx-cache-hook/
          rm -rf /tmp/.buildx-cache-ping
          cp -rn /tmp/.buildx-cache-pong/* /tmp/.buildx-cache-hook/
          rm -rf /tmp/.buildx-cache-pong
          mv /tmp/.buildx-cache-hook /tmp/.buildx-cache
